### ISSUE TITLE
Dogfood this application

### ISSUE THREAD

**Issue by sgerrand** [FundingCircle/shipment_tracker#8]
This application should use itself to have changes approved.

To facilitate this, the development workflow will probably need to change to use feature branches. I don't know what impact if any this will have.

Ping @FundingCircle/black-bat for :thought_balloon:s and :memo:s.

**Comment by dideler** [comment]
We've thought about this but haven't done it yet because Shipment Tracker itself doesn't need to be audited and because of the tension Pull Requests put on our continuous integration process. I realize we may be missing some obvious pain points or flaws by not dogfooding so at some point we probably should.

**Comment by sgerrand** [comment]
> Shipment Tracker itself doesn't need to be audited

@whamilton42: Is that true? Who watches the watchers? :thought_balloon:

**Comment by andistuder** [comment]
@sgerrand we were keen to roll fast and furious in the early phase of this project. But given this app is now in production, I agree that we should treat it as such. 

Timing is good: we have new team members joining next week and I will propose to start working with a more formal process - pending review with @dideler @whamilton42

**Comment by dideler** [comment]
We've started doing this.
